#docker-compose file is used to define the services, networks, and volumes for the application.

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      # [::1]: is the IPv6 loopback address
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      # CORS_ALLOWED_ORIGINS is a comma-separated list of origins allowed to make cross-site HTTP requests
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  #     - REACT_APP_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
  #   depends_on:
  #     - backend

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=localexplorer
      - POSTGRES_USER=localexplorer
      - POSTGRES_PASSWORD=localexplorer

volumes:
  postgres_data: